#!/bin/bash

DIR=$(pwd)

ln -sf /etc/runit/sv/NetworkManager /run/runit/service

clear

error () { clear

read -p "

Input yang anda masukkan salah !

" input
	case $input in
		*) return
		;;
	esac
}

# Membuat user baru
set-new-user () { clear

	read -p "

Masukkan username baru :

" nama

	read -p "

Apakah anda ingin menjadikan $nama menjadi user baru ? [Y/n] :

" yn

		case $yn in
			[Y/y]*) useradd -m $nama -G wheel
			chown -R $nama /home/$nama
			passwd $nama
			read -p "

Apakah anda ingin menjadikan $nama menjadi sudoer? [Y/n] :

" sudo
				case $sudo in
					[Yy]*) vim /etc/sudoers
					;;
					[Nn]*) return
					;;
					*) error
					;;
				esac
			;;
			[N/n]*) return
			;;
			*) error
			;;
		esac
}

# Enable services
set-services () { clear

	read -p "

Apakah anda ingin mengaktifkan Ntp, Cups, dan Ssh ? [Y/n] :

" yn

		case $yn in
			[Y/y]*) nmtui
			ln -sf /etc/runit/sv/ntpd /run/runit/service
			ln -sf /etc/runit/sv/cupsd /run/runit/service
			ln -sf /etc/runit/sv/sshd /run/runit/service

			echo "

Services sudah berhasil diaktifkan.

"
			pacman -Syyu --noconfirm
			;;
			[N/n]*) return
			;;
			*) error
			;;
		esac
}

# Menu setelah reboot
echo "
################################################################################
##                   ARTIX LINUX UTILITIES script by Reddof                   ##
################################################################################
##                               SETELAH REBOOT                               ##
##                                                                            ##
##  1. Enable NetworkManager Reflector dan Cups service                       ##
##  2. Set user baru                                                          ##
##  q. Kembali ke menu sebelumnya                                             ##
##                                                                            ##
##                                                                            ##
##                                                                            ##
##                                                                            ##
################################################################################
"

read -p "
Silakan masukkan pilihan anda : " ar
	case $ar in
		1) set-services
		;;
		2) set-new-user
		;;
		[Qq]*) exit
		;;
		*) error
		;;
	esac

$DIR/sub/inst.d/./after-inst
