#!/bin/bash

DIR=$(pwd)

clear

error () { clear

read -p "

Input yang anda masukkan salah !

" input
	case $input in
		*) return
		;;
	esac
}

# Membuat file fstab
set-fstab () { clear

	read -p "

lanjut membuat file Fstab ? [Y/n] :

" yn

		case $yn in
			[Y/y]*) fstabgen -U /mnt > /mnt/etc/fstab
			cat /mnt/etc/fstab
			;;
			[N/n]*) return
			;;
			*) error
			;;
		esac
}

# Install base dan packages pendukung
set-base () { clear
	read -p "

Pilih salah satu kernel yang ingin di install,
Official Kernel : linux, linux-zen, linux-lts, linux-hardened,
linux-rt, linux-rt-lts

" kernel

	read -p "

Lanjut install $kernel dan Package pendukung [Y/n] :

" yn

		case $yn in
			[Yy]*) basestrap /mnt base base-devel elogind-runit runit $kernel linux-firmware intel-ucode plymouth os-prober cups cups-runit cups-pdf networkmanager networkmanager-runit vim ntfs-3g man-db ntp ntp-runit openssh openssh-runit --overwrite "*"
			;;
			[Qq]*) return
			;;
			*) error
			;;
		esac
}

# Base Install Menu
echo "
################################################################################
##                   ARTIX LINUX UTILITIES script by Reddof                   ##
################################################################################
##                               BASE INSTALL                                 ##
##                                                                            ##
##  1. Install Base Kernel dan Packages Pendukung                             ##
##  2. Membuat File Fstab                                                     ##
##  q. Kembali ke Menu Sebelumnya                                             ##
##                                                                            ##
##                                                                            ##
##                                                                            ##
##                                                                            ##
################################################################################
"

read -p "

Silakan masukkan pilihan anda :

" util
	case $util in
		1) set-base
		;;
		2) set-fstab
		;;
		[Qq]*) exit
		;;
		*) error
	esac

$DIR/sub/inst.d/./base-inst
