#!/bin/bash

DIR=$(pwd)

clear

error () { clear

read -p "

Input yang anda masukkan salah !

" input
	case $input in
		*) return
		;;
	esac
}

# Install dan konfigurasi Grub
set-grub () { clear

	read -p "

Lanjut Install dan konfigurasi GRUB ? [Y/n] :

" yn

		case $yn in
			[Yy]*) pacman -S grub efibootmgr os-prober plymouth --noconfirm --noprogressbar --overwrite "*"
			rm -rf /etc/mkinitcpio.conf
			cp $DIR/sub/inst.d/src/mkinitcpio.conf /etc
			rm -rf /etc/default/grub
			cp $DIR/sub/inst.d/src/grub /etc/default
			read -p "

Masukkan mount point partisi efi anda, misalnya /boot/efi :

" efi

			read -p "

Masukkan bootloader id anda, misalnya 'Arch Linux' :

" bootloaderid

			grub-install --efi-directory=$efi --bootloader-id=$bootloaderid
			grub-mkconfig -o /boot/grub/grub.cfg
			;;
			[Nn]*) return
			;;
			*) error
			;;
		esac
}

# Setting Bahasa
set-bahasa () { clear

	read -p "

Masukkan kode bahasa utama anda, misalnya en_US untuk US English :

" bahasa1

	read -p "

Masukkan kode bahasa kedua anda, misalnya id_ID untuk Bahasa Indonesia :

" bahasa2

	read -p "

Apakah anda ingin Set bahasa anda ke $bahasa1.UTF-8 UTF-8 dan $bahasa2.UTF-8 UTF-8 ? [Y/n]

" yn

		case $yn in
			[Y/y]*) echo "$bahasa1.UTF-8 UTF-8" >> /etc/locale.gen
			echo "$bahasa2.UTF-8 UTF-8" >> /etc/locale.gen
			locale-gen
			echo "LANG=$bahasa1.UTF-8" > /etc/locale.conf
			;;
			[N/n]*) return
			;;
			*) error
			;;
		esac
}

# Setting Hostname
set-hostname () { clear

	read -p "

Masukkan hostname anda :

" hostname

	read -p "

Apakah anda ingin $hostname menjadi hostname anda ? [Y/n] :

" yn

		case $yn in
			[Y/y]*) echo "$hostname" > /etc/hostname
			;;
			[N/n]*) return
			;;
			*) error
			;;
		esac
}

# Setting timezone
set-timezone () { clear

	read -p "


Masukkan region anda diawali huruf kapital, misalnya Asia :


" region

	read -p "


Masukkan kota anda diawali huruf kapital, misalnya Jakarta :


" kota

	read -p "

Apakah anda ingin mengatur zona waktu ke $region/$kota ? [Y/n] :

" yn

		case $yn in
			[Y/y]*) ln -sf /usr/share/zoneinfo/$region/$kota /etc/localtime
			hwclock -w -l
			;;
			[N/n]*) return
			;;
			*) error
			;;
		esac
}

# Setting password root
set-password () { clear
	cp -R $DIR/sub/inst.d/src/.zsh* /root
	cp -R $DIR/sub/.oh* /root
	read -p "

Apakah ingin set password root anda ? [Y] :

" yn

		case $yn in
			[Y/y]*) passwd
			;;
			*) error
			;;
		esac
}

# Post Install Menu
echo "
################################################################################
##                   ARTIX LINUX UTILITIES script by Reddof                   ##
################################################################################
##                            POST INSTALL MENU                               ##
##                                                                            ##
##  1. Setting password root                                                  ##
##  2. Setting waktu dan timezone Asia/Jakarta                                ##
##  3. Mengatur hostname                                                      ##
##  4. Mengatur bahasa                                                        ##
##  5. Install dan konfigurasi grub                                           ##
##  q. Kembali ke menu sebelumnya                                             ##
##                                                                            ##
################################################################################
"

read -p "
Silakan masukkan pilihan anda : " post

	case $post in
		1) set-password
		;;
		2) set-timezone
		;;
		3) set-hostname
		;;
		4) set-bahasa
		;;
		5) set-grub
		;;
		[Qq]*) exit
		;;
		*) error
		;;
	esac

$DIR/sub/inst.d/./post-inst
