#!/bin/bash

DIR=$(pwd)
PAC_DIR="$(pwd)/sub/pac-man.d"

clear

error () { clear

read -p "

Input yang anda masukkan salah !

" input
	case $input in
		*) return
		;;
	esac
}

# List Files
set-listfiles () { clear

read -p "

Masukkan nama package untuk mengetahui
files apa saja yang yang dimiliki
package tersebut.
Masukkan nama package :

" pf
sudo pacman -Ql $pf

read -p "

s. Cari Package lain :

q. Kembali ke menu sebelumnya :

Pilihan anda :

" exit

	case $exit in
		[Ss]*) set-listfiles
		;;
		[Qq]*) return
		;;
		*) error
		;;
	esac
}

# Install package
set-install () { clear

	read -p "

Masukkan nama Package yang ingin diinstall :

" package

sudo pacman -Sy $package --asdep --noconfirm --overwrite "*"

read -p "

s. Install Package Lain :

q. Kembali ke menu sebelumnya :

Pilihan anda :

" exit

	case $exit in
		[Qq]*) return
		;;
		[Ss]*) set-install
		;;
		*) error
		;;
	esac
}

# Search dan Info package
set-packinfo () { clear


read -p "

Masukkan nama Package yang anda cari :

" package

echo "
Hasil Pencarian Terinstall:
"
sudo pacman -Qsq $package
echo "

Hasil Pencarian di repo :

"
sudo pacman -Ssq $package
echo "

Package Terinstall :

"
sudo pacman -Qi $package
echo "

Package di repo :

"
sudo pacman -Si $package

read -p "

s. Cari lagi

q. Kembali ke menu sebelumnya

Pilihan anda :

" exit

	case $exit in
		[Qq]*) return
		;;
		[Ss]*) set-packinfo
		;;
		*) error
		;;
	esac
}

# Update semua packages
set-updater () { clear

read -p "

Apakah ingin update semua packages ? [Y/n]

" yn

	case $yn in
		[Yy]*) sudo pacman -Syyu --asdeps --noconfirm --overwrite "*"
		;;
		[Nn]*) return
		;;
		*) error
		;;
	esac
}

echo "
################################################################################
##                   ARTIX LINUX UTILITIES script by Reddof                   ##
################################################################################
##                             INSTALL PACKAGES                               ##
##                                                                            ##
##  1. Update Packages                                                        ##
##  2. Cari dan Info Package                                                  ##
##  3. Install Package                                                        ##
##  4. Daftar Files dari Package                                              ##
##  5. Package Software Harian                                                ##
##  q. Kembali ke Menu Sebelumnya                                             ##
##                                                                            ##
##                                                                            ##
################################################################################
"

read -p "

Silakan masukkan pilihan anda :

" pa
	case $pa in
		1) set-updater
		;;
		2) set-packinfo
		;;
		3) set-install
		;;
		4) set-listfiles
		;;
		5) $PAC_DIR/./daily
		;;
		[Qq]*) exit
		;;
		*) error
		;;
	esac

$DIR/sub/./pac-man
